spring.application.name=easylease
ftp.server=easylease-stl.com
ftp.port=21
ftp.user=jose@easylease-stl.com
ftp.password=your_password_here
ftp.incoming-dir=/public_ftp/incoming
ftp.public-dir=/public_html/