package com.catalogo.easylease.enums;

public enum ExcelColumn {
    PACK_BUSINESS_TIPO(64),
    ENTRADA_SIN_IVA(12),
    IMAGEN(21),
    MODELO(22),
    ACABADO(23),
    CUOTA_MENSUAL_SIN_IVA(24),
    CUOTA_MENSUAL_CON_IVA(25),
    MESES_PLAZO_CUOTAS(26),
    KMS_TOTALES(28),
    COMISION_APERTURA_PORCENTAJE(29),
    COMISION_APERTURA_CON_IVA(30),
    COMISION_APERTURA_SIN_IVA(31),
    TIN(32),
    TAE(33),
    ULTIMA_CUOTA_SIN_IVA(34),
    ULTIMA_CUOTA_CON_IVA(35),
    PRECIO_FINANCIADO_CON_IVA(36),
    PRECIO_FINANCIADO_SIN_IVA(37),
    INTERESES_CON_IVA(38),
    INTERESES_SIN_IVA(39),
    COSTE_TOTAL_CON_IVA(40),
    COSTE_TOTAL_SIN_IVA(41),
    FIANZA(43),
    FECHA_VALIDEZ(45),
    CONSUMO(46),
    ENTRADA_CON_IVA(48),
    CUOTA_CON_PACK_BUSINESS(49),
    PACK_BUSINESS_VALOR(50),
    CUOTA_SEGURO_AUTO(51),
    CUOTA_MANTENIMIENTO(52),
    CUOTA_GESTION_MULTAS(53),
    KMS_MANTENIMIENTO(62),
    DURACION_MANTENIMIENTO(63),
	PACK_BUSINESS(64);

    private final int index;
    ExcelColumn(int index) { this.index = index; }
    public int getIndex() { return index; }
}